setRepeat(0);
addFrame('|', 250);
addFrame('', 250);
addFrame('|', 250);
addFrame('', 250);
addFrame('|', 250);
addFrame('', 250);
addFrame('|', 250);
addFrame('', 250);
addFrame('|', 250);
addFrame('H|', 100);
addFrame('He|', 100);
addFrame('Hel|', 100);
addFrame('Hell|', 100);
addFrame('Hello|', 100);
addFrame('Hello.|', 250);
addFrame('Hello.', 250);
addFrame('Hello.|', 250);
addFrame('Hello.', 250);
addFrame('Hello.|', 250);
addFrame('Hello.\n|', 250);
addFrame('Hello.\n', 250);
addFrame('Hello.\n|', 250);
addFrame('Hello.\nH|', 100);
addFrame('Hello.\nHo|', 100);
addFrame('Hello.\nHow|', 100);
addFrame('Hello.\nHow |', 100);
addFrame('Hello.\nHow a|', 100);
addFrame('Hello.\nHow ar|', 100);
addFrame('Hello.\nHow are|', 100);
addFrame('Hello.\nHow are |', 100);
addFrame('Hello.\nHow are y|', 100);
addFrame('Hello.\nHow are yo|', 100);
addFrame('Hello.\nHow are you|', 100);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?', 250);
addFrame('Hello.\nHow are you?|', 250);
addFrame('Hello.\nHow are you?\n|', 250);
addFrame('Hello.\nHow are you?\nG|', 100);
addFrame('Hello.\nHow are you?\nGl|', 100);
addFrame('Hello.\nHow are you?\nGla|', 100);
addFrame('Hello.\nHow are you?\nGlad|', 100);
addFrame('Hello.\nHow are you?\nGlad |', 100);
addFrame('Hello.\nHow are you?\nGlad t|', 100);
addFrame('Hello.\nHow are you?\nGlad to|', 100);
addFrame('Hello.\nHow are you?\nGlad to |', 100);
addFrame('Hello.\nHow are you?\nGlad to h|', 100);
addFrame('Hello.\nHow are you?\nGlad to he|', 100);
addFrame('Hello.\nHow are you?\nGlad to hea|', 100);
addFrame('Hello.\nHow are you?\nGlad to hear|', 100);
addFrame('Hello.\nHow are you?\nGlad to hear |', 100);
addFrame('Hello.\nHow are you?\nGlad to hear i|', 100);
addFrame('Hello.\nHow are you?\nGlad to hear it|', 100);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!|', 250);
addFrame('Hello.\nHow are you?\nGlad to hear it!', 250);
addFrame('              x', 250);
addFrame('              5               $\n              x', 250);
addFrame('    %         #               !\n    ¬         *               f\n              5               $\n              @', 250);
addFrame('    -         #      ^        e                               ÿ\n    %         #               }\n    ¬         *               f\n              5               $\n              @', 250);
addFrame('    *         .      |        s                               y\n    -         #      ^        e                               ÿ\n    %         #               !\n    ¬         *               f\n              5               $\n              @', 250);
addFrame('              _      3        ¯             s                 k\n    *         .      |        s                               y\n    -         #      ^        e                               ÿ\n    %         @               !\n    ¬         *               i\n              5               $\n              n', 250);
addFrame('      \\       :      $                      h                 ^\n              _      3        ¯             s                 k\n    *         .      |        s                               y\n    -         #      ^        e                               ÿ\n    %         @               !\n    ¬         *               i\n              5               $\n              n', 250);
addFrame('      /              "        =             \\                 >\n      \\       :      $                      h                 ^\n              _      3        ¯             s                 k\n    *         .      |        s                               y\n    -         #      ^        E                               ÿ\n    &         @               !\n    ¬         *               i\n              5               $\n              n', 250);
addFrame('      /              "        =             \\                 >\n      \\       :      $                      h                 ^\n              _      3        ¯             s                 k\n    *         .      |        s                               y\n    -         #      ^        E                               ÿ\n    &         @               !\n    ¬         *               i\n              5               $\n              n\n\n', 2500);
addFrame('      /              "        =             \\                 >\n      \\       :      $                      h                 ^\n              _      3        ¯             s                 k\n    *         .      |        s                               y\n    -         #      ^        E                               ÿ\n    &         @               !\n    ¬         *               i\n              5               $\n              n                __________________\n                               |  SYSTEM ERROR  |\n                               ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\n\n', 250);
